### ISSUE TITLE
Use SafeMath in MANACrowdsale.sol Constructor Function

### ISSUE THREAD

**Issue by cintixverum** [decentraland/mana#12]
Line 44:

`require(_rate > _rateStepDecrease * (_endBlock - _startBlock));`

 and line 78 of MANACrowdsale.sol:

`return rate.sub(rateStepDecrease.mul(block.number - startBlock));`

should use SafeMath functions to be consistent with the rest of the codebase.

Specifically, line 44 should be changed to:

`require(_rate > _rateStepDecrease.mul(_endBlock.sub(_startBlock)));`

and line 78 should be changed to:

`return rate.sub(rateStepDecrease.mul(block.number.sub(startBlock)));`

**Comment by federicobond** [comment]
Thank you! This code was removed from the constructor function as the rate calculation is changed.

**Comment by maraoz** [comment]
Severity assigned: low
