### ISSUE TITLE
Overflow Analysis TODO Removal

### ISSUE THREAD

**Issue by cintixverum** [decentraland/mana#13]
Line 127 of MANACrowdsale.sol:

`// TODO: possibility of overflow in these operations should be analized`

should be removed as there is no possibility of overflow.  uint256 can store numbers larger than 10^77.

The line also contains a typo: analized should be analyzed.

It's also worth noting that the interest in the next two lines is calculated linearly instead of exponentially.

**Comment by kylerschin** [comment]
Stupid Overflow.

**Comment by federicobond** [comment]
Yes, indeed, the 8% annual inflation is computed based on the supply at the end of the crowdsale and remains constant after that.

Thank you for taking a look at it @cintixverum!
