### ISSUE TITLE
Consider adding comments on OpenZeppelin import versions

### ISSUE THREAD

**Issue by veox** [decentraland/mana#14]
In [MANACrowdsale.sol](https://github.com/decentraland/mana/blob/fd0c0a7574b44adafeffbe6033ef2bb6450921c2/contracts/MANACrowdsale.sol#L3) three contracts are imported from `zeppelin-solidity`, but there's no indication as to which versions they are.

This potentially complicates review.

**Comment by maraoz** [comment]
You can see that in https://github.com/decentraland/mana/blob/master/package.json#L10
