### ISSUE TITLE
processPurchase() && getRate()

### ISSUE THREAD

**Issue by AugustoL** [decentraland/mana#16]
processPurchase() in MANACrowdsale overrides the function in ContiniousCrowdsale, Instead of overriding that method you can add the function getRate() on the ConiousCrowdsale and only override that function, I understand that is the only thing that you want to do, provide different rates for special addresses, its not a bug, just a change on the code that you can do, and I think It will look better.

Also, why is getRate() internal? I think it can be public, so the investors can verify the rate they are going to have before sending eth.

If you want I can create the PR, let me know what you think :)

**Comment by federicobond** [comment]
This is fixed with the split of the continuous sale.

**Comment by maraoz** [comment]
Severity assigned: low
