### ISSUE TITLE
burnTokens() public

### ISSUE THREAD

**Issue by AugustoL** [decentraland/mana#17]
DO you want to allow the token holders to burn/destroy their tokens? Maybe you dont, I mean you want the tokens in circulation right? Would a user would want to destroy it?. In the case a account is hacked, and instead of draining the account the attacker decide to burn the tokens instead.

I dont understand 100% how you crowdsale will work, but if you need to destroy unsold tokens, you can allow only the crowdsale owner to do that.

If you want I can create the PR to let only the owner of the crowdsale burn tokens, let me know what you think :)

**Comment by AugustoL** [comment]
@maraoz @eordano are the tokens used to buy or represent land? In case of tokens being destroyed how it will affect decentraland?

**Comment by maraoz** [comment]
NACK. All token holders can burn tokens

**Comment by jashmenn** [comment]
Maybe I'm missing something, but it looks like there is no upper bound on `burn`. The way I read the code you could burn the whole supply by passing a large `_value`. 

Shouldn't we add `require(_value <= balances[burner])` on line 19?

**Comment by federicobond** [comment]
Closing this.
