### ISSUE TITLE
Implement PausableToken for MANA

### ISSUE THREAD

**Issue by eordano** [decentraland/mana#22]
The MANA token should be pausable

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/PausableToken.sol

**Comment by maraoz** [comment]
ACK, ping @federicobond

**Comment by federicobond** [comment]
Pausable is Ownable, but the token is owned by the Crowdsale contract. We can forward those  pause/unpause calls via pauseToken/unpauseToken methods in the crowdsale.

**Comment by maraoz** [comment]
IMO, token should be paused right after construction, and only unpaused manually after the crowdsale ends, via the foundation's multisig, probably proxying through the continous token sale contract.

**Comment by maraoz** [comment]
@federicobond can you implement this?
@eordano comments?

**Comment by maraoz** [comment]
@federicobond @eordano there doesn't seem to be a way to unpause the token with current version

**Comment by federicobond** [comment]
That seems to be the case. We are missing the proxy calls to pause/unpause from the MANAContinuousSale contract which owns the token.

**Comment by maraoz** [comment]
@federicobond token should be paused on token sale contructor, as explained here: https://github.com/decentraland/mana/issues/22#issuecomment-318045622

**Comment by federicobond** [comment]
Fixed in #30
