### ISSUE TITLE
Off by one error in rateStepDecrease precondition

### ISSUE THREAD

**Issue by frangio** [decentraland/mana#27]
Since `endBlock` is inclusive, [MANACrowdsale.sol:44](https://github.com/decentraland/mana/blob/master/contracts/MANACrowdsale.sol#L44) should read:

```
require(_rate > _rateStepDecrease * (1 + _endBlock - _startBlock));
```

**Comment by federicobond** [comment]
This was fixed but superseded by the new rate calculation.
