### ISSUE TITLE
Split main crowdsale from continuous sale contract

### ISSUE THREAD

**Issue by federicobond** [decentraland/mana#9]
We should transfer the ownership of the token once the main Crowdsale ends to a simpler contract that only handles the continuous issuance. This significantly reduces the attack surface of both contracts.

**Comment by maraoz** [comment]
Agreed

**Comment by eordano** [comment]
+1

**Comment by kylerschin** [comment]
+1 :+1:

**Comment by federicobond** [comment]
Pull request here: https://github.com/decentraland/mana/pull/24

**Comment by federicobond** [comment]
PR merged.
